<p>
    <a href="<?=$this->url(array('m'=>'instructor','c'=>'challenges'))?>">Challenges</a>
    >
    <b>Edit</b>
</p>

<div class="info">   
    <p><b>Challenge:</b> <?=$this->challenge['name']?></p>
    <p><b>Theme:</b> <?=$this->challenge['theme']?></p>
    <p><b>Start:</b> <?=date('m/d/Y, H:i:s', strtotime($this->challenge['start']))?></p>
    <p><b>End:</b> <?=date('m/d/Y, H:i:s', strtotime($this->challenge['end']))?></p>
</div>

<?if(!$this->form):?>

<p class="ok">Challenge edited</p>

<?else:?>

<?=$this->form?>

<?endif;?>