<p>
    <a href="<?=$this->url(array('m'=>'instructor','c'=>'challenges'))?>">Challenges</a>
    >
    <a href="<?=$this->url(array('m'=>'instructor','c'=>'challenges','a'=>'teams','id'=>$this->challenge['id']))?>">Teams</a>
    >
    <b>Members</b>
</p>

<div class="info">
    <p><b>Challenge:</b> <?=$this->challenge['name']?></p>
    <p><b>Theme:</b> <?=$this->challenge['theme']?></p>
    <p><b>Start:</b> <?=date('m/d/Y, H:i:s', strtotime($this->challenge['start']))?></p>
    <p><b>End:</b> <?=date('m/d/Y, H:i:s', strtotime($this->challenge['end']))?></p>
</div>

<div class="info">
    <p><b>Team:</b> <?=$this->team['name']?></p>
</div>

<?if(count($this->members) == 0):?>

<p class="ko">No members</p>

<?else:?>

<table>
    <tr>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Email</th>
        <th>Role</th>
    </tr>
    <?foreach($this->members as $m):?>
    <tr>
        <td><?=$m['LastName']?></td>
        <td><?=$m['FirstName']?></td>
        <td><?=$m['Email']?></td>
        <td><?=$m['role']?></td>
    </tr>
    <?endforeach;?>
</table>

<?endif;?>