<p>
    <a href="<?=$this->url(array('m'=>'instructor','c'=>'challenges'))?>">Challenges</a>
    >
    <b>Teams</b>
</p>

<div class="info">
    <p><b>Challenge:</b> <?=$this->challenge['name']?></p>
    <p><b>Theme:</b> <?=$this->challenge['theme']?></p>
    <p><b>Start:</b> <?=date('m/d/Y, H:i:s', strtotime($this->challenge['start']))?></p>
    <p><b>End:</b> <?=date('m/d/Y, H:i:s', strtotime($this->challenge['end']))?></p>
</div>

<?if(count($this->teams) == 0):?>

<p>No teams</p>

<?else:?>

<table>
    <tr>
        <th>Name</th>
        <th># members</th>
        <th>Score</th>
        <th></th>
    </tr>
    <?foreach($this->teams as $t):?>
    <tr>
        <td><?=$t['name']?></td>
        <td><?=$t['members']?></td>
        <td><?=$t['score']?></td>
        <td><a href="<?=$this->url(array('m'=>'instructor','c'=>'challenges','a'=>'members','id'=>$t['id']))?>">Members</a></td>
    </tr>
    <?endforeach;?>
</table>

<?endif;?>
