<p>
    <a href="<?=$this->url(array('m'=>'admin','c'=>'accounts'))?>">Accounts</a>
    >
    <b>Edit</b>
</p>

<div class="info">
    <p><b>First name:</b> <?=$this->account->FirstName?></p>
    <p><b>Last name:</b> <?=$this->account->LastName?></p>
    <p><b>Email:</b> <?=$this->account->Email?></p>
    <p><b>User Level:</b> <?=$this->account->UserLevel?></p>
</div>

<?if(!$this->form):?>

<p class="ok">Account edited</p>

<?else:?>

<?=$this->form?>

<?endif;?>