<p>Hello <?=$this->firstName?>!</p>

<p>These are your credential to access in INspect-Web:</p>

<table>
    <tr>
        <td><b>Email:</b></td>
        <td><?=$this->email?></td>
    </tr>
    <tr>
        <td><b>Password:</b></td>
        <td><?=$this->password?></td>
    </tr>
</table>

<!--<p><a href="http://cc.ics.uci.edu/inspectweb/" target="_blank">Click here</a> to access INspect-Web.</p>-->

<p>These are your credential to access in INspect-World:</p>

<table>
    <tr>
        <td><b>Username:</b></td>
        <td><?=$this->firstName?> <?=$this->lastName?></td>
    </tr>
    <tr>
        <td><b>Password:</b></td>
        <td><?=$this->password?></td>
    </tr>
</table>
