<p>
    <b>Students</b>
    >
    <b>List</b>
</p>

<?if(count($this->students) == 0):?>

<p>No students</p>

<?else:?>

<table>
    <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    <?foreach($this->students as $s):?>
    <tr>
        <td><?=$s->FirstName?></td>
        <td><?=$s->LastName?></td>
        <td><?=$s->Email?></td>
        <td><a href="<?=$this->url(array('m'=>'instructor','c'=>'students','a'=>'edit','id'=>$s->UUID))?>">Edit</a></td>
        <td><a href="<?=$this->url(array('m'=>'instructor','c'=>'students','a'=>'delete','id'=>$s->UUID))?>">Delete</a></td>
    </tr>
    <?endforeach;?>
</table>

<?endif;?>
