<p>
    <b>Challenges</b>
    >
    <b>Themes</b>
</p>

<?if(count($this->themes) == 0):?>

<p class="ko">No themes</p>

<?else:?>

<table>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    <?foreach($this->themes as $t):?>
    <tr>
        <td><?=$t['name']?></td>
        <td><?=nl2br($t['description'])?></td>
        <td><a href="<?=$this->url(array('m'=>'instructor','c'=>'themes','a'=>'steps','id'=>$t['id']))?>">Steps</a></td>
        <td><a href="<?=$this->url(array('m'=>'instructor','c'=>'themes','a'=>'edit','id'=>$t['id']))?>">Edit</a></td>
        <td><a href="<?=$this->url(array('m'=>'instructor','c'=>'themes','a'=>'delete','id'=>$t['id']))?>">Delete</a></td>
    </tr>
    <?endforeach;?>
</table>

<?endif;?>
