<p>
    <a href="<?=$this->url(array('m'=>'instructor','c'=>'account'))?>">Account</a>
    >
    <b>Edit Password</b>
</p>

<div class="info">
    <p><b>First name:</b> <?=$this->account->FirstName?></p>
    <p><b>Last name:</b> <?=$this->account->LastName?></p>
    <p><b>Email:</b> <?=$this->account->Email?></p>
</div>

<?if(!$this->form):?>

<p class="ok">Password edited</p>

<?else:?>

<?=$this->form?>

<?endif;?>