<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title>INspect-Web Authentication</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        <link rel="stylesheet" href="pub/css/reset.css" />
        <link rel="stylesheet" href="pub/css/auth/layout.css" />
        <link rel="stylesheet" href="pub/css/auth/input.css" />
        <script type="text/javascript" src="pub/js/jquery-1.8.2.min.js"></script>
        <script type="text/javascript">
            $(function() {
                $("input[type=text]").first().focus();
                $("input[type=text]").attr("autocomplete", "off");
            });
        </script>
    </head>
    <body>
        <h1>INspect-Web Authentication</h1>
        <?if($this->user):?>
        <p class="ok">Hello <?=$this->user->FirstName?> <?=$this->user->LastName?></p>
        <p>Wait... redirecting!</p>
        <?else:?>
        <form method="POST">
            <table>
                <tr>
                    <th>Email:</th>
                    <td><input type="text" name="email" /></td>
                </tr>
                <tr>
                    <th>Password:</th>
                    <td><input type="password" name="password" /></td>
                </tr>
                <tr>
                    <th></th>
                    <td><input type="submit" name="submit" value="Login" /></td>
                </tr>
            </table>
        </form>
        <?endif;?>
    </body>
</html>