<p>
    <b>Challenges</b>
    >
    <a href="<?=$this->url(array('m'=>'instructor','c'=>'teams'))?>">Teams</a>
    >
    <b>Members</b>
</p>

<div class="info">
    <p><b>Team:</b> <?=$this->team['name']?></p>
</div>

<?if(!$this->form):?>

<p class="ok">Member added</p>

<?endif;?>

<?=$this->form?>

<?if(count($this->members) == 0):?>

<p class="ko">No members</p>

<?else:?>

<table>
    <tr>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Email</th>
        <th>Role</th>
        <th></th>
        <th></th>
    </tr>
    <?foreach($this->members as $m):?>
    <tr>
        <td><?=$m['LastName']?></td>
        <td><?=$m['FirstName']?></td>
        <td><?=$m['Email']?></td>
        <td><?=$m['role']?></td>
        <td><a href="<?=$this->url(array('m'=>'instructor','c'=>'teams','a'=>'edit-member','id'=>$m['id']))?>">Edit role</a></td>
        <td><a href="<?=$this->url(array('m'=>'instructor','c'=>'teams','a'=>'delete-member','id'=>$m['id']))?>">Remove</a></td>
    </tr>
    <?endforeach;?>
</table>

<?endif;?>